= Abgabe 1
:author: Florian Weingartshofer 
:email: <S1910307103@students.fh-hagenberg.at>
:reproducible:
:listing-caption: Listing
:source-highlighter: rouge


== MinMax
=== Lösungsidee
==== minmax (main)
Durchläuft die Commandline-Parameter, diese werden zu einem Integer geparsed.
Der Integer wird mit dem momentanen maximal und minimal Wert verglichen, welche mit 0 initialisiert sind.
Sollte dieser größer oder kleiner sein, werden Min oder Max mit dem neuen überschrieben.
Am Ende werden die Werte von Min und Max ausgegeben.

==== parse_int
Nutzt die `sscanf` Funktion um eine Zeichenkette zu einen Integer zu parsen. 
Ist der Status Code 1, wird der erfolgreich geparste Integer zurückgegeben.
Falls nicht wird das Programm abgebrochen und eine Fehlernachricht ausgegeben.
Allerdings werden Zahlen nicht korrekt geparst wenn ein Buchstabe in der Zahl selber ist.

=== Testfälle
==== 01
[source]
----
./minmax
Min: 0
Max: 0
----

==== 02
[source]
----
./minmax 10 100 1000
Min: 0
Max: 1000
----

==== 03
[source]
----
./minmax -10 -100 -1000
Min: -1000
Max: 0
----

==== 04
[source]
----
./minmax 10 -10 100 -100
Min: -100
Max: 100
----

==== 05
[source]
----
./minmax asdf
asdf is not an int
----

==== 06
[source]
----
./minmax asdf10
asdf10 is not an int
----

==== 07
Anmerkung: Hier sieht man die Fehler bei der `sscanf` Funktion.
[source]
----
./minmax 1asdf0
Min: 0
Max: 1
----


==== 07
Anmerkung: Hier sieht man die Fehler bei der `sscanf` Funktion.
[source]
----
./minmax 10asdf
Min: 0
Max: 10
----

=== Source Code
[source,c]
----
include::../src/minmax/minmax.c[]
----

== Primfaktorzerlegung
=== Lösungsidee
==== main
Als erstes wird die Breite der Spalten für die Ausgabe berechnet.
Dafür wird die Länge des längsten Commandline-Parameter genutzt, mithilfe der `strlen` Funktion.
Dann werden die Commandline-Parameter geparsed und der `prime_factorization` Funktion übergeben.

==== parse_int
Gleich wie bei `minmax`.

==== prime_factorization
Führt die Primfaktorzerlegung aus. Als erstes wird die übergebene Zahl `n` auf Spezialfälle 0 und 1 überprüft.
Sollten diese nicht zutreffen, wird `n` solange durch 2 geteilt, bis es ungerade Zahl ist.
Nach jedem mal Teilen wird `n` auf das Ergebnis der Division gesetzt.
Wie oft geteilt wird, wird mitgezählt. Dieses Ergebnis wird gleich ausgegeben.

Danach wird `n` durch alle ungeraden Zahlen von 3 bis zur Wurzel von `n` geteilt. 
Für die Wurzel wird die `math` Library Funktion `sqrt` genutzt. 
Damit eine Executable gebaut werden kann, wird der `-lm` Switch bei `gcc` benötigt.
Wie oft `n` durch eine Zahl geteilt werden kann, wird mitgezählt, 
danach wird der Teiler und Teiler-Anzahl ausgegeben.
`n` wird wieder auf das Ergebnis der Division gesetzt.

Am Ende wird `n` noch überprüft ob es größer als 2 ist, 
sollte dies der Fall sein, ist `n` noch eine Primzahl und wird ausgegeben.

=== Testfälle
==== 01
[source]
----
./factorinteger

----

==== 02
[source]
----
./factorinteger 350000 0 42 1 65537
350000: {{2,4},{5,5},{7,1}}
     0: {{0,1}}
    42: {{2,1},{3,1},{7,1}}
     1: {{1,1}}
 65537: {{65537,1}}
----

==== 03
[source]
----
./factorinteger asdf
asdf is not an int
----

==== 04
[source]
----
./factorinteger 1asdf0
     1: {{1,1}}
----

==== 05
[source]
----
./factorinteger 10asdf
    10: {{2,1},{5,1}}
----

==== 06
[source]
----
./factorinteger -10
The numbers should be positive
----

==== 07
[source]
----
./factorinteger -
- is not an int
----

==== 08
Anmerkung: Das Asterisk `*` wird in der Bash zu allen lokalen Files expandiert und als Argumente übergeben, 
z.B. `./factorinteger *` -> `./factorinteger factorinteger factorinteger.c Makefile`. 
[source]
----
./factorinteger *
factorinteger is not an int
----

==== Source Code
[source,c]
----
include::../src/prim/factorinteger.c[]
----

